ALTER TABLE engineers ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE engineers ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE engineers ADD COLUMN IF NOT EXISTS password TEXT;
ALTER TABLE engineers ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT false;
ALTER TABLE engineers ADD COLUMN IF NOT EXISTS project_codes TEXT[];
