/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#264191",
        "tertiary-container": "#384055",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#131b2e",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#783200",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#00164e",
        "secondary-fixed": "#ffdbca",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-container": "#e5eeff",
        "on-secondary-fixed": "#341100",
        "surface-container-highest": "#d3e4fe",
        "on-surface-variant": "#444651",
        "surface-container-high": "#dce9ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#dae2fd",
        "on-secondary-container": "#5c2400",
        "secondary-container": "#fd761a",
        "outline-variant": "#c5c5d3",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-container": "#90a8ff",
        "primary": "#00236f",
        "background": "#f8f9ff",
        "inverse-primary": "#b6c4ff",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "primary-container": "#1e3a8a",
        "on-background": "#0b1c30",
        "error-container": "#ffdad6",
        "primary-fixed": "#dce1ff",
        "secondary": "#9d4300",
        "on-tertiary-container": "#a4acc5",
        "inverse-on-surface": "#eaf1ff",
        "tertiary": "#222a3e",
        "outline": "#757682",
        "inverse-surface": "#213145",
        "surface-container-low": "#eff4ff",
        "secondary-fixed-dim": "#ffb690",
        "on-secondary": "#ffffff",
        "surface-tint": "#4059aa",
        "on-surface": "#0b1c30"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "4px",
        "grid-margin": "24px",
        "md": "16px",
        "grid-gutter": "16px",
        "xl": "32px",
        "xs": "4px",
        "sm": "8px",
        "lg": "24px"
      },
      fontFamily: {
        "title-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
