CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. BẢNG MATERIAL_PLANS (Kế hoạch vật tư)
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS parent_id UUID;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS project_code TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS project_name TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS stt TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS job_content TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS unit TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS contract_volume NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS tech_spec_model TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS tech_spec_origin TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS tech_spec_status TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS progress_status TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS ordered_volume NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS ordered_status TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS expected_date DATE;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS issue_content TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS issue_status TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS doc_co BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS doc_cq BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS doc_fire_inspection BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS doc_stamp BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS dispatch_to_site BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS dispatch_date DATE;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS supply_scope TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS material_plans ADD COLUMN IF NOT EXISTS updated_by TEXT;

-- 2. BẢNG PURCHASING_PLANS (Kế hoạch mua hàng)
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS material_plan_id UUID;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS project_code TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS project_name TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS stt TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS job_content TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS unit TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS volume_contract NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS volume_order NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS unit_price NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS vat_rate NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS vat_amount NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS total_amount NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS prepay_percent NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS prepay_amount NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS remaining_amount NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS order_status TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS contract_status TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS payment_date DATE;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS invoice_status TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS supplier TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS supplier_quote NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS selected_supplier TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS expected_date DATE;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS delivery_date DATE;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS section_name TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS parent_id UUID;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS cost_paid_amount NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS cost_payment_date DATE;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS cost_payment_method TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS cost_payer_name TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS purchasing_plans ADD COLUMN IF NOT EXISTS updated_by TEXT;

-- Đồng bộ dữ liệu cũ nếu trước đó dùng cột job_content
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='purchasing_plans' AND column_name='job_content') THEN
        UPDATE purchasing_plans SET content = job_content WHERE content IS NULL OR content = '';
    END IF;
END $$;

-- 3. BẢNG ACTIVITY_LOGS (Lịch sử hoạt động)
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS user_name TEXT;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS "user" TEXT;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS project TEXT;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS project_code TEXT;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS project_name TEXT;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS project_id UUID;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS icon TEXT;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS badge_bg TEXT;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS icon_color TEXT;
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS activity_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- 4. BẢNG ATTENDANCE_LOGS (Chấm công)
CREATE TABLE IF NOT EXISTS attendance_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT,
    user_name TEXT DEFAULT '',
    project_id TEXT,
    project_name TEXT,
    check_in_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    check_out_time TIMESTAMP WITH TIME ZONE,
    check_in_image TEXT,
    check_out_image TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. BẢNG EXPENSES
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS project_code TEXT;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS requester TEXT;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS updated_by TEXT;

-- 6. BẢNG TASKS
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS project_code TEXT;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS project_name TEXT;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS purchase_status TEXT DEFAULT '';
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS constr_status TEXT DEFAULT '';
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS issue TEXT;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS issue_status TEXT;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS is_section_header BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS section_name TEXT;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS parent_id UUID;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS assigned_engineer_id UUID;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS assigned_engineer_name TEXT;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS assigner_id UUID;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS assigner_name TEXT;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS reviewer_id UUID;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS reviewer_name TEXT;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS updated_by TEXT;

-- 7. NẠP LẠI CACHE SCHEMA CỦA SUPABASE POSTGREST
NOTIFY pgrst, 'reload schema';